name: Backend CI

on:
  pull_request:
    paths:
      - 'src/main/java/**'
  push:
    paths:
      - 'src/main/java/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Enable debug mode
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: 'main'

      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
          architecture: x64

      - name: Change file permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        env:
          MONGO_URI: ${{ secrets.MONGODB_URI }},
          MONGO_DBNAME: ${{ secrets.MONGODB_DBNAME }}
        run: |
          chmod +x ./gradlew
          ./gradlew build --exclude-task test --warning-mode=all --stacktrace 
          File='file:///home/runner/work/messaner/messaner/build/reports/***s/***/index.html'
          if [ -f '$FILE' ]; then
            cat '$FILE'
          else
            echo '$FILE does not exist.'
          fi
          chmod 755 ${{ env.BUILD_PATH }}