name: Backend CI

on:
  pull_request:
    paths:
      - 'src/main/java/**'
  push:
    paths:
      - 'src/main/java/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: 'main'

      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
          architecture: x64

      - name: Change file permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        run: ./gradlew build --stacktrace

      - name: Run test
        run: ./gradlew :test

      - name: Run checkstyle
        run: ./gradlew checkstyleMain

