name: CD workflow

on:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      BUILD_DIR: "messaner/build/libs/"

    steps:
      - name: Enable debug mode
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
          architecture: x64

      - name: Set NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Change file permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        env:
          MONGO_URI: ${{ secrets.MONGODB_URI }},
          MONGO_DBNAME: ${{ secrets.MONGODB_DBNAME }}
        run: |
          ./gradlew build --warning-mode=all --stacktrace 
          File='file:///home/runner/work/messaner/messaner/build/reports/***s/***/index.html'
          if [ -f "$FILE" ]; then
            cat "$FILE"
          else
            echo '$FILE does not exist.'
          fi

      - name: Setup React
        run: |
          cd src/main/resources/react-dev
          npm audit fix && npm install
          npm run build && cd ../../../../

      - name: Check files before transfer
        run: ls -la ./${{ env.BUILD_DIR }}

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          source: "./${{ env.BUILD_DIR }}messaner-0.0.1-SNAPSHOT.jar"
          target: "~/${{ env.BUILD_DIR }}"
          overwrite: true

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar ~/${{ env.BUILD_DIR }}messaner-0.0.1-SNAPSHOT.jar > ~/messaner/logs 2>&1 & EOF
