name: Frontend CI

on:
  pull_request:
    paths:
      - 'src/main/resources/react-dev/**'
  push:
    paths:
      - 'src/main/resources/react-dev/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Enable debug mode
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd src/main/resources/react-dev
          npm audit fix && npm install && npm run build
          npx eslint .